name: meta-rauc CI

on:
  # Trigger the workflow on push or pull request,
  # but only for the scarthgap branch
  push:
    branches:
      - scarthgap
  pull_request:
    branches:
      - scarthgap
jobs:
  build:
    name: meta-rauc Build
    runs-on: ubuntu-20.04
    timeout-minutes: 720
    steps:
      - name: Install required packages
        run: |
          sudo apt-get install diffstat
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: meta-rauc
      - name: Clone poky
        run: git clone -b scarthgap git://git.yoctoproject.org/poky
      - name: Clone meta-openembedded
        run: git clone -b scarthgap https://github.com/openembedded/meta-openembedded.git
      - name: Initialize build directory
        run: |
          source poky/oe-init-build-env build
          bitbake-layers add-layer ../meta-rauc
          echo 'INHERIT += "rm_work"' >> conf/local.conf
          echo 'DISTRO_FEATURES:remove = "alsa bluetooth usbgadget usbhost wifi nfs zeroconf pci 3g nfc x11 opengl ptest wayland vulkan"' >> conf/local.conf
          echo 'SSTATE_MIRRORS = "file://.* http://195.201.147.117/sstate-cache/PATH"' >> conf/local.conf
      - name: Build rauc, rauc-native
        run: |
          source poky/oe-init-build-env build
          bitbake rauc rauc-native
      - name: Build rauc-hawkbit-updater
        run: |
          source poky/oe-init-build-env build
          bitbake rauc-hawkbit-updater
      - name: Build dt-utils
        run: |
          source poky/oe-init-build-env build
          bitbake dt-utils
      - name: Build casync, casync-native
        run: |
          source poky/oe-init-build-env build
          bitbake-layers add-layer ../meta-openembedded/meta-oe
          bitbake-layers add-layer ../meta-openembedded/meta-python
          bitbake-layers add-layer ../meta-openembedded/meta-networking
          bitbake-layers add-layer ../meta-openembedded/meta-filesystems
          bitbake casync casync-native
      - name: Build rauc-hawkbit
        run: |
          source poky/oe-init-build-env build
          bitbake-layers add-layer ../meta-openembedded/meta-python
          bitbake rauc-hawkbit
